### ISSUE TITLE
[branch: namespace] Exception thrown on Install

### ISSUE THREAD

**Issue by franck-paul** [JcDenis/dotclear#3]
```
Fatal error: Uncaught Error: Class "Dotclear\Database\Driver\Mysqli" not found in […]/htdocs/git-dc3/src/Database/Driver/Mysqlimb4/Connection.php:27
Stack trace:
#0 […]/htdocs/git-dc3/src/Utils/Autoloader.php(234): require()
#1 […]/htdocs/git-dc3/src/Utils/Autoloader.php(215): Dotclear\Utils\Autoloader->requireFile('...')
#2 […]/htdocs/git-dc3/src/Utils/Autoloader.php(184): Dotclear\Utils\Autoloader->loadMappedFile('Dotclear\\', 'Database\\Driver...')
#3 [internal function]: Dotclear\Utils\Autoloader->loadClass('Dotclear\\Databa...')
#4 […]/htdocs/git-dc3/src/Database/Connection.php(53): class_exists('Dotclear\\Databa...')
#5 […]/htdocs/git-dc3/src/Install/Wizard.php(85): Dotclear\Database\Connection::init('mysqlimb4', 'localhost', 'dc3', 'root', 'root')
#6 […]/htdocs/git-dc3/src/Install/Prepend.php(44): Dotclear\Install\Wizard->__construct()
#7 […]/htdocs/git-dc3/src/Core/Core.php(150): Dotclear\Install\Prepend->process(NULL)
#8 […]/htdocs/git-dc3/src/Dotclear.php(69): Dotclear\Core\Core::coreInstance(NULL)
#9 […]/htdocs/git-dc3/src/Dotclear.php(82): Dotclear->__construct('Install', NULL)
#10 […]/htdocs/git-dc3/admin/install.php(13): Dotclear::__callStatic('Install', Array)
#11 {main} thrown in […]/htdocs/git-dc3/src/Database/Driver/Mysqlimb4/Connection.php on line 27
```

Env:

MAMP on MacOS with:

*   PHP 8.1
*   MySQL 5.7 (using a uft8mb4 database)
*   Apache

**Comment by JcDenis** [comment]
Dans php.ini tu utilises le module mysqli ou pdo_mysqli ?
J'ai souvenir que j'avais eu ça et en bricolant le php.ini + ses modules, c'était passé

**Comment by JcDenis** [comment]
Comme pour PgSql, php 8.1 doit introduire des modifications de **ressource** en des **Class**

**Comment by JcDenis** [comment]
ah on c'est ma faute

**Comment by franck-paul** [comment]
\\o/ Problem solved!
